const MEDIA_CATALOG = {
  "Historical Photos": [
    { name: "Before PRH photos/before-prh-1.jpeg", type: "jpeg", video: false },
    { name: "Before PRH photos/before-prh-10.jpeg", type: "jpeg", video: false },
    { name: "Before PRH photos/before-prh-100.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-101.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-102.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-103.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-104.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-105.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-106.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-107.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-108.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-11.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-111.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-112.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-113.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-116.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-117.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-118.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-119.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-120.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-121.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-122.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-123.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-124.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-125.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-126.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-127.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-128.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-129.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-130.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-131.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-132.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-133.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-134.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-135.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-136.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-137.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-138.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-139.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-140.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-141.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-142.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-143.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-144.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-145.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-146.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-147.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-148.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-149.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-150.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-151.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-152.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-153.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-154.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-155.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-156.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-157.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-158.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-159.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-160.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-161.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-162.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-163.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-164.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-165.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-166.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-167.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-168.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-169.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-170.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-171.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-172.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-173.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-174.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-175.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-176.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-177.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-178.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-179.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-180.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-181.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-182.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-183.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-184.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-185.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-186.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-187.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-188.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-189.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-190.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-191.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-192.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-193.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-194.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-195.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-196.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-197.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-198.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-199.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-200.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-201.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-202.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-203.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-3.png", type: "png", video: false },
    { name: "Before PRH photos/before-prh-4.jpeg", type: "jpeg", video: false },
    { name: "Before PRH photos/before-prh-6.png", type: "png", video: false },
    { name: "Before PRH photos/before-prh-9.png", type: "png", video: false },
    { name: "Before PRH photos/before-prh-109.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-110.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-114.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-12.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-13.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-14.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-15.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-16.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-17.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-18.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-19.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-2.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-20.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-204.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-205.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-206.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-207.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-208.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-209.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-21.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-22.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-23.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-24.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-25.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-26.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-27.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-28.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-29.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-30.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-31.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-32.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-33.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-34.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-35.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-36.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-37.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-38.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-39.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-40.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-41.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-42.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-43.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-44.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-45.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-46.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-47.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-48.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-49.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-5.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-50.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-51.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-52.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-53.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-54.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-55.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-56.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-57.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-58.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-59.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-60.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-61.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-62.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-63.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-64.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-65.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-66.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-67.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-68.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-69.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-7.jpeg", type: "jpeg", video: false },
    { name: "Before PRH photos/before-prh-70.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-71.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-72.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-73.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-74.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-75.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-76.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-77.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-78.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-79.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-8.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-80.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-81.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-82.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-83.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-84.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-85.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-86.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-87.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-88.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-89.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-90.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-91.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-92.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-93.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-94.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-95.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-96.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-97.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-98.jpg", type: "jpg", video: false },
    { name: "Before PRH photos/before-prh-99.jpg", type: "jpg", video: false }
  ]
,
  "Construction": [
    { name: "building.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-1.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-10.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-2.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-3.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-4.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-5.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-6.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-7.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-8.jpg", type: "jpg", video: false },
    { name: "construction-painting/construction-painting-9.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-10.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-11.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-12.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-13.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-14.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-15.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-16.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-17.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-18.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-19.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-2.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-20.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-21.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-22.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-23.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-25.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-26.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-27.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-28.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-29.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-3.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-30.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-31.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-32.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-33.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-34 (2).jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-34.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-35.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-36.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-37.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-38.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-39.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-4.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-40.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-41.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-42.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-43.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-44.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-45.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-46.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-47.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-48.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-49.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-5.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-50.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-53.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-6.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-7.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-8.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-9.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-1.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-51.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-52.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-54.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-55.jpg", type: "jpg", video: false },
    { name: "construction-photos/construction-photos-56.jpg", type: "jpg", video: false },
    { name: "materials.jpg", type: "jpg", video: false },
    { name: "painting-work.jpg", type: "jpg", video: false }
  ]
,
  "Modern Facilities": [
    { name: "computer-class.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-10.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-11.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-12.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-13.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-14.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-17.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-18.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-19.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-20.jpg", type: "jpg", video: false },
    { name: "computer-room/computer-room.jpg", type: "jpg", video: false },
    { name: "lockers-photos/locker-photos-1.jpg", type: "jpg", video: false },
    { name: "lockers-photos/locker-photos-2.jpg", type: "jpg", video: false },
    { name: "lockers-photos/locker-photos-3.jpg", type: "jpg", video: false },
    { name: "lockers-photos/locker-photos-4.jpg", type: "jpg", video: false },
    { name: "lockers-photos/locker-photos-5.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-1.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-2.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-3.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-4.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-5.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-6.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-7.jpg", type: "jpg", video: false },
    { name: "modern-office/modern-office-8.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-1.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-2.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-3.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-4.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-5.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-6.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-7.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-8.jpg", type: "jpg", video: false },
    { name: "solar-panels/solar-panels-9.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-1.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-15.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-2.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-3.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-4.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-5.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-6.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-7.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-8.jpg", type: "jpg", video: false },
    { name: "computer-classes/computer-classes-9.jpg", type: "jpg", video: false },
    { name: "computer-room.jpg", type: "jpg", video: false },
    { name: "modern-office-1.jpg", type: "jpg", video: false },
    { name: "solar-panels-3.jpg", type: "jpg", video: false }
  ]
,
  "Feeding Program": [
    { name: "feeding-program/feeding-program-1.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-10.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-11.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-12.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-13.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-14.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-15.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-16.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-17.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-18.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-19.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-2.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-20.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-21.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-22.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-23.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-24.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-25.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-26.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-27.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-28.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-29.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-3.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-30.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-31.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-32.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-33.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-34.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-35.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-36.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-37.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-38.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-39.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-4.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-40.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-41.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-42.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-43.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-44.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-45.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-49.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-50.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-51.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-6.mp4", type: "mp4", video: true },
    { name: "feeding-program/feeding-program-8.mp4", type: "mp4", video: true },
    { name: "kids-eating.jpg", type: "jpg", video: false },
    { name: "kids-enjoying-food-5.jpg", type: "jpg", video: false },
    { name: "kids-enjoying-food-8.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-10.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-11.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-12.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-2.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-3.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-4.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-6.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-7.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-9.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-46.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-47.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-48.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-5.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-52.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-53.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-54.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-55.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-56.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-57.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-58.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-59.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-60.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-61.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-62.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-63.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-64.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-65.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-66.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-67.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-68.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-69.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-7.jpg", type: "jpg", video: false },
    { name: "feeding-program/feeding-program-9.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-1.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-5.jpg", type: "jpg", video: false },
    { name: "kids-enjoyingfood/kids-enjoying-food-8.jpg", type: "jpg", video: false }
  ]
,
  "Educational Trips": [
    { name: "educational-trip.jpg", type: "jpg", video: false },
    { name: "glorious-educational-trip-1.mp4", type: "mp4", video: true },
    { name: "glorious-educational-trip-10.jpg", type: "jpg", video: false },
    { name: "glorious-educational-trip-5.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-10.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-12.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-13.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-14.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-15.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-16.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-17.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-18.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-19.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-2.mp4", type: "mp4", video: true },
    { name: "glorious-educationaltrip/glorious-educational trip-21.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-22.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-23.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-1.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-11.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-20.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-24.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-26.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-27.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-28.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-29.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-3.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-30.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-4.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-5.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-7.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-8.jpg", type: "jpg", video: false },
    { name: "glorious-educationaltrip/glorious-educational trip-9.jpg", type: "jpg", video: false }
  ]
,
  "Exams & Academics": [
    { name: "certificate-graduation/certificate-graduation-1.jpg", type: "jpg", video: false },
    { name: "certificate-graduation/certificate-graduation-2.jpg", type: "jpg", video: false },
    { name: "certificate-graduation/certificate-graduation-3.jpg", type: "jpg", video: false },
    { name: "exams.jpg", type: "jpg", video: false },
    { name: "internal-exams/internal-exam-1.jpg", type: "jpg", video: false },
    { name: "internal-exams/internal-exam-2.jpg", type: "jpg", video: false },
    { name: "internal-exams/internal-exam-3.jpg", type: "jpg", video: false },
    { name: "internal-exams/internal-exam-4.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-10.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-11.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-12.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-13.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-14.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-15.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-16.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-17.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-2.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-3.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-4.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-5.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-6.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-7.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-8.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-9.jpg", type: "jpg", video: false },
    { name: "certificate-graduation/certificate-graduation-4.jpg", type: "jpg", video: false },
    { name: "certificate-graduation/certificate-graduation-5.jpg", type: "jpg", video: false },
    { name: "certificate-graduation/certificate-graduation-6.jpg", type: "jpg", video: false },
    { name: "national-exams/national-exams-1.jpg", type: "jpg", video: false },
    { name: "national-exams.jpg", type: "jpg", video: false }
  ]
,
  "Community & Relief": [
    { name: "bigrelief-mukuru/bigrelief-mukuru-1.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-10.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-11.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-12.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-13.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-14.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-15.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-16.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-17.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-18.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-2.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-26.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-27.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-28.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-29.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-30.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-31.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-32.jpg", type: "jpg", video: false },
    { name: "church-roof/church-roof-2.jpg", type: "jpg", video: false },
    { name: "church-roof/church-roof-4.jpg", type: "jpg", video: false },
    { name: "community-blessing.jpg", type: "jpg", video: false },
    { name: "deserted-families/deserted-families-1.jpg", type: "jpg", video: false },
    { name: "deserted-families/deserted-families-2.jpg", type: "jpg", video: false },
    { name: "god-blessyou/godblessyou-docsott-1.jpg", type: "jpg", video: false },
    { name: "god-blessyou/godblessyou-docsott-2.jpg", type: "jpg", video: false },
    { name: "god-blessyou/godblessyou-docsott-3.jpg", type: "jpg", video: false },
    { name: "god-blessyou/godblessyou-docsott-4.jpg", type: "jpg", video: false },
    { name: "health-awareness.jpg", type: "jpg", video: false },
    { name: "healthcare.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-19.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-20.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-21.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-22.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-23.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-24.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-25.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-3.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-33.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-34.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-35.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-36.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-4.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-5.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-6.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-7.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-8.jpg", type: "jpg", video: false },
    { name: "bigrelief-mukuru/bigrelief-mukuru-9.jpg", type: "jpg", video: false },
    { name: "church-roof/church-roof-5.jpg", type: "jpg", video: false },
    { name: "church-roof/church-roof-7.jpg", type: "jpg", video: false },
    { name: "deserted-families.jpg", type: "jpg", video: false }
  ]
,
  "General Photos": [
    { name: "beautiful-school/beautiful-school-1.jpg", type: "jpg", video: false },
    { name: "beautiful-school/beautiful-school-2.jpg", type: "jpg", video: false },
    { name: "beautiful-school/beautiful-school-3.jpg", type: "jpg", video: false },
    { name: "more-photos-1.jpg", type: "jpg", video: false },
    { name: "more-photos-2.jpg", type: "jpg", video: false },
    { name: "more-photos.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-10.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-11.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-12.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-13.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-14.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-15.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-16.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-17.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-18.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-19.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-20.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-21.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-22.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-23.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-24.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-25.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-26.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-27.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-28.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-29.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-30.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-31.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-32.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-33.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-34.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-35.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-36.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-37.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-38.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-39.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-40.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-41.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-42.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-43.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-44.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-45.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-46.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-47.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-48.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-49.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-50.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-51.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-7.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-8.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-9.jpg", type: "jpg", video: false },
    { name: "beautiful-school/beautiful-school-4.jpg", type: "jpg", video: false },
    { name: "beautiful-school/beautiful-school-6.jpg", type: "jpg", video: false },
    { name: "beautiful-school/beautiful-school-7.jpg", type: "jpg", video: false },
    { name: "construction-photos-10.jpg", type: "jpg", video: false },
    { name: "construction-photos-50.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-1.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-2.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-3.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-4.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-5.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-52.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-53.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-54.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-55.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-56.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-57.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-58.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-59.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-6.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-60.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-61.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-62.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-63.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-64.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-65.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-66.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-67.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-68.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-69.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-70.jpg", type: "jpg", video: false },
    { name: "more-pics/more-photos-71.jpg", type: "jpg", video: false },
    { name: "more-pics.jpg", type: "jpg", video: false },
    { name: "photos-1.jpg", type: "jpg", video: false },
    { name: "photos-2.jpg", type: "jpg", video: false },
    { name: "photos-3.jpg", type: "jpg", video: false },
    { name: "photos-4.jpg", type: "jpg", video: false },
    { name: "photos-5.jpg", type: "jpg", video: false },
    { name: "photos-6.jpg", type: "jpg", video: false },
    { name: "photos-7.jpg", type: "jpg", video: false }
  ]
,
  "Student Life": [
    { name: "orphans/orphans-1.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-10.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-11.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-12.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-13.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-14.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-15.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-16.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-17.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-2.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-3.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-4.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-5.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-6.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-7.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-8.jpg", type: "jpg", video: false },
    { name: "orphans/orphans-9.jpg", type: "jpg", video: false },
    { name: "orphans.jpg", type: "jpg", video: false }
  ]
,
  "Student Profiles": [
    { name: "Student Profiles/Abberlyn Kailyn, 2.png", type: "png", video: false },
    { name: "Student Profiles/Abigail Amanda, 7.png", type: "png", video: false },
    { name: "Student Profiles/Alex Barasa, 14.png", type: "png", video: false },
    { name: "Student Profiles/Alexander Ngui, 16.png", type: "png", video: false },
    { name: "Student Profiles/Amina Suleiman.png", type: "png", video: false },
    { name: "Student Profiles/Angel Nafula, 4.png", type: "png", video: false },
    { name: "Student Profiles/Asha Siraj, 14.png", type: "png", video: false },
    { name: "Student Profiles/Bamka Absolom, 6.png", type: "png", video: false },
    { name: "Student Profiles/Baraka Bisau, 6.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/bella moraa, 4.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Blessing Stephen, 5.png", type: "png", video: false },
    { name: "Student Profiles/bolt kasiti, 13.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Brigda Ndanu, 14.png", type: "png", video: false },
    { name: "Student Profiles/Cynthia Momanyi, 14.png", type: "png", video: false },
    { name: "Student Profiles/Daniel Wanyonyi, 17.png", type: "png", video: false },
    { name: "Student Profiles/David Mwendwa, 16.png", type: "png", video: false },
    { name: "Student Profiles/Delight Awuor, 15.png", type: "png", video: false },
    { name: "Student Profiles/dennis mutuku, 9.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/diana obiero, 12.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Diana Simiyu, 12.png", type: "png", video: false },
    { name: "Student Profiles/dolphin kwamboka,13.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Emmanuel Luchivya, 13.png", type: "png", video: false },
    { name: "Student Profiles/emmanuel mtinda,10.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/esther moraa, 11.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/faith nanjama, 13.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Faith Sarah Mary, 14.png", type: "png", video: false },
    { name: "Student Profiles/Favor Joy, 5.png", type: "png", video: false },
    { name: "Student Profiles/Geoffrey Muthoka, 16.png", type: "png", video: false },
    { name: "Student Profiles/Glen Harrison, 13.png", type: "png", video: false },
    { name: "Student Profiles/Goodluck Musela, 7.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Hannah Mueni, 16.png", type: "png", video: false },
    { name: "Student Profiles/Hellen Koli, 10.png", type: "png", video: false },
    { name: "Student Profiles/hosea braving ndagwa, 11.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Immanuel Saramba, 17.png", type: "png", video: false },
    { name: "Student Profiles/Joy Ayuma, 4.png", type: "png", video: false },
    { name: "Student Profiles/Kelvin Wanjala, 12.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/kendrick wadabwa, 4.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Kevin Mwendwa, 16.png", type: "png", video: false },
    { name: "Student Profiles/maximilla chepyagon, 5.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/mercy wairimu, 10.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/michelle auma, 9.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Miriam Lynne Namaemba, 10.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/morgan okello, 12.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/mumo musyoka, 11.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Patrick Mohammed, 16.png", type: "png", video: false },
    { name: "Student Profiles/Pellar Omwoyo, 6.png", type: "png", video: false },
    { name: "Student Profiles/rachel mutheu, 13.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Rose Zaitun Mmbone, 14.png", type: "png", video: false },
    { name: "Student Profiles/Samuel Amani, 5.jpg", type: "jpg", video: false },
    { name: "Student Profiles/Shadrack Omukuba, 14.png", type: "png", video: false },
    { name: "Student Profiles/Shananzy Nafula, 4.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/sheila kwamboka, 8.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Sherill Miheso, 4.jpeg", type: "jpeg", video: false },
    { name: "Student Profiles/Shidado Barongo, 15.png", type: "png", video: false },
    { name: "Student Profiles/Timothy Wafula, 10.png", type: "png", video: false },
    { name: "Student Profiles/Victoria Kioko, 15.png", type: "png", video: false },
    { name: "Student Profiles/yvonne ndanu, 15.jpeg", type: "jpeg", video: false }
  ]
,
  "Leadership": [
    { name: "profile-drscott.jpg", type: "jpg", video: false },
    { name: "profile.-bonface-mangeti.png", type: "png", video: false }
  ]
,
  "Videos": [
    { name: "balcony-videos/balcony-videos-1.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-10.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-11.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-12.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-13.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-14.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-15.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-16.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-2.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-3.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-4.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-5.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-6.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-7.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-8.mp4", type: "mp4", video: true },
    { name: "balcony-videos/balcony-videos-9.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-1.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-10.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-11.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-12.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-13.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-14.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-15.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-16.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-2.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-3.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-4.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-5.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-6.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-7.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-8.mp4", type: "mp4", video: true },
    { name: "electrical-engineering/electrical-engineering-videos-9.mp4", type: "mp4", video: true }
  ]
,
  "Construction Videos": [
    { name: "construction-videos/construction-viudeos-67.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-68.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-69.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-70.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-71.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-72.mp4", type: "mp4", video: true },
    { name: "construction-videos/construction-viudeos-73.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-1.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-10.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-11.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-12.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-13.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-14.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-15.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-16.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-17.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-18.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-19.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-2.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-20.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-21.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-22.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-23.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-24.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-25.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-26.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-27.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-28.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-29.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-3.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-30.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-31.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-32.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-33.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-34.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-35.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-36.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-37.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-38.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-39.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-4.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-40.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-41.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-42.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-43.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-44.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-45.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-46.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-47.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-48.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-49.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-5.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-50.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-51.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-52.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-53.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-54.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-55.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-56.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-57.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-58.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-59.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-6.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-60.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-61.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-62.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-63.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-64.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-65.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-66.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-7.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-8.mp4", type: "mp4", video: true },
    { name: "construction-videos/contruction-videos-9.mp4", type: "mp4", video: true }
  ]
,
  "Hero Images": [
    { name: "IMG-20251011-WA0149.jpg", type: "jpg", video: false }
  ]
};

const CATEGORY_ORDER = [
  "Historical Photos",
  "Construction",
  "Modern Facilities",
  "Feeding Program",
  "Educational Trips",
  "Exams & Academics",
  "Community & Relief",
  "General Photos",
  "Student Life",
  "Student Profiles",
  "Leadership",
  "Videos",
  "Construction Videos",
  "Hero Images"
];
